package card

sealed case class CardPack(name: String)
final object SteelRebellion extends CardPack("Steel Rebellion")
final object Alterspher extends CardPack("Altersphere")
final object OmenOfTheten extends CardPack("Omen of the Ten")
final object BrigadeOfTheSky extends CardPack("Brigade of the Sky")
final object DawnbreakNightedge extends CardPack("Dawnbreak, Nightedge")
final object Chronogenesis extends CardPack("Chronogenesis")
final object StarforgedLegends extends CardPack("Starforged Legends")
final object WonderlandDreams extends CardPack("Wonderland Dreams")
final object TempestOfTheGods extends CardPack("Tempest of the Gods")
final object RiseOfBahamut extends CardPack("Rise of Bahamut")
final object DarknessEvolved extends CardPack("Darkness Evolved")
final object Classic extends CardPack("Classic")
final object Basic extends CardPack("Basic")
final object PrebuiltDecksSet1 extends CardPack("Prebuilt Decks Set 1")
final object PrebuiltDecksSet2 extends CardPack("Prebuilt Decks Set 2")
final object AnigeraDidoooonTieIn extends CardPack("Anigera Didoooon Tie-In")
final object FateStayNightHeavensFeelTieIn extends CardPack("Fate/stay night [Heaven's Feel] Tie-in")
final object PrebuiltDecksSet4 extends CardPack("Prebuilt Decks Set 4")
final object PrebuiltDecksSet5 extends CardPack("Prebuilt Decks Set 5")
final object PrincessConnectRediveTieIn extends CardPack("Princess Connect! Re:Dive Tie-in")
final object OnePunchManTieIn extends CardPack("One-Punch Man Tie-in")


